const api = window.electronAPI || {}

export const getConfig = () => api.getConfig?.() || Promise.resolve({})
export const getPackageInfo = () => api.getPackageInfo?.() || Promise.resolve({})
export const saveConfig = (config) => api.saveConfig?.(config) || Promise.resolve(false)
export const generateScript = (scriptInfo) => api.generateScript?.(scriptInfo) || Promise.resolve({ success: false, error: 'API not available' })
export const openFile = (filePath) => api.openFile?.(filePath) || Promise.resolve(false)
export const openFolder = (folderPath) => api.openFolder?.(folderPath) || Promise.resolve(false)
export const selectDirectory = () => api.selectDirectory?.() || Promise.resolve('')
export const selectFile = () => api.selectFile?.() || Promise.resolve('')
export const reloadConfig = () => api.reloadConfig?.() || Promise.resolve({})
export const reloadMenu = () => api.reloadMenu?.() || Promise.resolve(false)
export const setAutoStart = (enable) => api.setAutoStart?.(enable) || Promise.resolve(false)
export const getAutoStart = () => api.getAutoStart?.() || Promise.resolve(false)
export const checkForUpdates = (manual) => api.checkForUpdates?.(manual) || Promise.resolve({ status: 'dev-environment' })
export const openSettings = (tab) => api.openSettings?.(tab) || Promise.resolve(true)
export const closeSettingsWindow = () => api.closeSettingsWindow?.() || Promise.resolve()
export const readDirectory = (dirPath) => api.readDirectory?.(dirPath) || Promise.resolve({ success: false, error: 'API not available' })
export const copyToClipboard = (itemPath, recursive) => api.copyToClipboard?.(itemPath, recursive) || Promise.resolve(false)
export const getItemInfo = (itemPath) => api.getItemInfo?.(itemPath) || Promise.resolve({ success: false, error: 'API not available' })
export const chat = (messages, options) => api.chat?.(messages, options) || Promise.resolve({ success: false, error: 'API not available' })
export const validateApiKey = (providerType, apiKey, extraConfig) => api.validateApiKey?.(providerType, apiKey, extraConfig) || Promise.resolve(false)
export const getAiProviders = () => api.getAiProviders?.() || Promise.resolve([])
export const getProviderModels = (providerType) => api.getProviderModels?.(providerType) || Promise.resolve([])

// Database connection APIs
export const dbTestConnection = (config) => api.dbTestConnection?.(config) || Promise.resolve({ success: false, error: 'API not available' })
export const dbCreateConnection = (name, config) => api.dbCreateConnection?.(name, config) || Promise.resolve({ success: false, error: 'API not available' })
export const dbCloseConnection = (name) => api.dbCloseConnection?.(name) || Promise.resolve({ success: false, error: 'API not available' })
export const dbCloseAllConnections = () => api.dbCloseAllConnections?.() || Promise.resolve({ success: false, error: 'API not available' })
export const dbExecuteQuery = (name, sql, params, options) => api.dbExecuteQuery?.(name, sql, params, options) || Promise.resolve({ success: false, error: 'API not available' })
export const dbQueryDatabases = (name) => api.dbQueryDatabases?.(name) || Promise.resolve({ success: false, error: 'API not available' })
export const dbQueryTables = (name, database) => api.dbQueryTables?.(name, database) || Promise.resolve({ success: false, error: 'API not available' })
export const dbGetTableStructure = (name, database, tableName) => api.dbGetTableStructure?.(name, database, tableName) || Promise.resolve({ success: false, error: 'API not available' })
export const dbGetActiveConnections = () => api.dbGetActiveConnections?.() || Promise.resolve([])
export const dbIsConnectionActive = (name) => api.dbIsConnectionActive?.(name) || Promise.resolve(false)
export const dbBeginTransaction = (name) => api.dbBeginTransaction?.(name) || Promise.resolve({ success: false, error: 'API not available' })
export const dbCommitTransaction = (name) => api.dbCommitTransaction?.(name) || Promise.resolve({ success: false, error: 'API not available' })
export const dbRollbackTransaction = (name) => api.dbRollbackTransaction?.(name) || Promise.resolve({ success: false, error: 'API not available' })

export const selectSqlFile = () => api.selectSqlFile?.() || Promise.resolve({ canceled: true })
export const readFile = (filePath) => api.readFile?.(filePath) || Promise.resolve({ success: false, error: 'API not available' })
export const saveSqlFile = (defaultPath) => api.saveSqlFile?.(defaultPath) || Promise.resolve({ canceled: true })
export const writeFile = (filePath, content) => api.writeFile?.(filePath, content) || Promise.resolve({ success: false, error: 'API not available' })

export const onNavigateTo = (callback) => api.onNavigateTo?.(callback) || (() => {})
export const onUpdateStatus = (callback) => api.onUpdateStatus?.(callback) || (() => {})
export const onUpdateProgress = (callback) => api.onUpdateProgress?.(callback) || (() => {})
export const onConfigChanged = (callback) => api.onConfigChanged?.(callback) || (() => {})

export default api