const MIN_SPLASH_DISPLAY_TIME = 3000
const UPDATE_CHECK_INTERVAL = 12 * 60 * 60 * 1000
const VALID_CLOSE_ACTIONS = ['ask', 'hide', 'quit']
const VALID_OPERATE_TYPES = ['FIX', 'PUBLISH', 'QUERY']

module.exports = {
  MIN_SPLASH_DISPLAY_TIME,
  UPDATE_CHECK_INTERVAL,
  VALID_CLOSE_ACTIONS,
  VALID_OPERATE_TYPES,
}